# TODO (TV2): doi lai username/password khop voi may local cua ban
db.url=jdbc:mysql://localhost:3306/mail_system?useSSL=false&serverTimezone=UTC
db.username=root
db.password=your_password
server.port=5000
